project:
  type: website

website:
  title: "All About Me — Dummy Profile"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
  page-footer:
    left: "Made with 💜 using Quarto"

format:
  html:
    theme: darkly
    css: styles.css
    toc: false
